### ISSUE TITLE
iTerm 2 support

### ISSUE THREAD

**Issue by ValkyrieUK** [karan/atom-terminal#12]
Would be great if this would open a iTerm Terminal.

**Comment by nemonweb** [comment]
maybe this on config.cson file

"atom-terminal":
    app: "/Applications/iTerm.app"

**Comment by crucialfelix** [comment]
Still not working if you set a custom terminal. 

/Applications/iTerm.app does not work, /bin/bash with the script does not work either.

```
**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-terminal](https://github.com/karan/atom-terminal) package, v0.7.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/crucial/.atom/packages/atom-terminal/lib/atom-terminal.coffee:52

TypeError: undefined is not a function
  at Object.module.exports.open (/Users/crucial/.atom/packages/atom-terminal/lib/atom-terminal.coffee:52:32)
  at atom-workspace.<anonymous> (/Users/crucial/.atom/packages/atom-terminal/lib/atom-terminal.coffee:45:71)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
     -6:38.9 core:confirm (atom-text-editor.editor.mini)
     -6:38.9 atom-terminal:open (atom-text-editor.editor.vim-mode.command-mode)
     -5:42.2 core:close (div.settings-view.pane-item)
     -2:30.1 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:28.0 core:move-down (atom-text-editor.editor.mini)
     -2:27.7 core:confirm (atom-text-editor.editor.mini)
     -2:27.7 set-syntax:JSX (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:25.4 core:save (atom-text-editor.editor.vim-mode.command-mode.is-focused)
 11x -2:20.3 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -2:13.2 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -2:07.5 editor:consolidate-selections (atom-text-editor.editor.mini)
     -2:07.5 core:cancel (atom-text-editor.editor.mini)
  2x -2:06.6 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:06.1 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:03.5 core:confirm (atom-text-editor.editor.mini)
     -0:03.5 atom-terminal:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*.pyc",
      "static"
    ],
    "followSymlinks": true,
    "disabledPackages": [
      "cute-cursor",
      "grunt-runner",
      "language-go",
      "language-java",
      "syntax-settings",
      "term",
      "language-supercollider",
      "linter-rst",
      "rst-preview",
      "rst-preview",
      "linter",
      "atom-runner",
      "make-runner",
      "ide-haskell",
      "remote-edit",
      "atomatigit",
      "minimap",
      "autocomplete-paths",
      "minimap-highlight-selected",
      "tabs-to-spaces",
      "term2",
      "atomic-emacs",
      "git-log",
      "autoflow",
      "autosave",
      "background-tips",
      "block-travel",
      "dash",
      "easy-motion",
      "gist-it",
      "git-blame",
      "git-difftool",
      "git-plus",
      "emmet",
      "org",
      "trailing-spaces",
      "project-colorize",
      "file-icons",
      "autocomplete-plus",
      "ide-flow"
    ],
    "themes": [
      "isotope-ui",
      "afterglow-monokai-syntax"
    ],
    "destroyEmptyPanes": false
  },
  "atom-terminal": {
    "app": "/bin/bash"
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
afterglow-monokai-syntax, v1.3.2
angularjs, v0.1.0
atom-beautify, v0.23.2
atom-color-highlight, v3.0.8
atom-django, v0.2.1
atom-lint, v0.20.1
atom-terminal, v0.7.0
autoclose-html, v0.15.0
coffee-lint, v0.7.3
color-picker, v1.6.0
command-logger, v0.22.0
css-color-highlighting, v0.2.4
django-templates, v0.4.0
editor-stats, v0.17.0
editorconfig, v0.3.3
filetype-color, v0.1.4
highlight-selected, v0.9.1
isotope-ui, v2.0.1
javascript-snippets, v1.0.0
language-clojure, v0.13.0
language-docker, v1.1.3
language-jade, v0.3.0
language-restructuredtext, v0.4.0
last-cursor-position, v0.8.0
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-jscs, v1.9.0
linter-jshint, v0.1.0
linter-jsxhint, v0.1.1
linter-pep8, v0.1.0
linter-pylint, v0.2.1
linter-scss-lint, v0.0.14
minimap-find-and-replace, v4.2.0
pain-split, v1.3.1
project-manager, v1.15.5
quick-move-file, v0.7.0
react, v0.11.0
recent-files, v0.3.0
regex-railroad-diagram, v0.7.3
script, v2.18.0
selection-count, v1.6.3
set-syntax, v0.2.1
vim-mode, v0.42.0
web-browser, v1.4.2
web-view, v0.3.0
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by marcus-cr** [comment]
> maybe this on config.cson file
> 
> "atom-terminal":
> app: "/Applications/iTerm.app"

Works but launching iTerm with default profile _and_ the hotkey profile at same time...
