### ISSUE TITLE
Allow environment variable config

### ISSUE THREAD

**Issue by RangerMauve** [karan/atom-terminal#13]
Currently opening the terminal from atom screws up my `npm install` process because the `NODE_ENV` variable is set to `production` by atom. This makes npm ignore the `devDependencies` that I need for building my project.

Is there any chance we could get a way to set environment variables before launching the terminal? Or maybe just setting `NODE_ENV` to something else?

**Comment by robkorv** [comment]
This is also conflicting with my workflow. Is this something that can be fixed in atom-terminal?

**Comment by tkw1536** [comment]
If you are not on windows, you can try to use the following config: 

app: "/bin/bash"
args: "-c 'NODE_ENV=development;/usr/bin/x-terminal-emulator'"

I haven't tested this, but something like this should work.

**Comment by robkorv** [comment]
That works in Ubuntu 14.04! :cool:
