### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by syaning** [karan/atom-terminal#22]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (c:\Users\...\AppData\Local\atom\app-0.174.0\resources\app\src\atom.js:55:11)
Object.activate (c:\Users\...\.atom\packages\atom-terminal\lib\atom-terminal.coffee:45:13)
```

**Comment by alanmarcos** [comment]
I'm still having this issue:

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\...\AppData\Local\atom\app-0.181.0\resources\app\src\atom.js:54:11)
Object.activate (C:\Users\...\.atom\packages\atom-terminal\lib\atom-terminal.coffee:45:13)
```

**Comment by tkw1536** [comment]
Do you have the latest master installed? I removed that piece of the code: https://github.com/karan/atom-terminal/blob/master/lib/atom-terminal.coffee#L45

**Comment by alanmarcos** [comment]
I'd installed through the 'Settings' Menu. I've installed through command line and now it works just fine! Thanks!
