### ISSUE TITLE
Choose terminal app

### ISSUE THREAD

**Issue by andersennl** [karan/atom-terminal#24]
It would be useful to choose / set in package settings, which terminal app should be used. I for example use iTerm2, not the standard terminal on mac. Thanks.

**Comment by tkw1536** [comment]
There used be an option for that. It must have disappeared with one of the atom updates.

**Comment by andersennl** [comment]
Oh I see. Where in the package could I manually set this?

**Comment by tkw1536** [comment]
@andersennl In the source code. The option should be there, but it looks like one of the atom APIs changed something and now they are gone. The source for the options is in https://github.com/karan/atom-terminal/blob/master/lib/atom-terminal.coffee#L57-L84.

**Comment by andersennl** [comment]
Thanks lot @tkw1536
