### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by btd** [karan/atom-terminal#50]
Hello @karan. I see you have activity on github, but do not have any activity in this repo for 20 days. Maybe you will add collaborators?

**Comment by tkw1536** [comment]
+1 on this, there have been a lot of new issues lately and it would be great to get some of them fixed soon

**Comment by karan** [comment]
Pushing update in a few hours.

**Comment by karan** [comment]
https://github.com/karan/atom-terminal/commit/647119498b25105c3a0bac0f564a75d37d9d975b
