### ISSUE TITLE
Terminal does not open in directory when "Surpress Directory Argument" is set.

### ISSUE THREAD

**Issue by NemSavic** [karan/atom-terminal#52]
When "Surpress Directory Argument" is set my terminal only ever opens in my home directory, never in the file or project root directory. Disabling "Surpress Directory Argument" resolved the issue.  I tested it with with Terminal & iTerm

**Comment by axsann** [comment]
Maybe this is not a issue... this is probably right specification.
but many people perceive that this  phenomenon is issue.
This setting should set false as default. and explanatory label should change.
Fix please.

**Comment by braver** [comment]
Wow indeed. At least mention this in the readme!
