### ISSUE TITLE
Dangerous environment variables being set

### ISSUE THREAD

**Issue by rubencaro** [karan/atom-terminal#53]
I noticed my node related commands showing unexpected output when run from terminals opened with this. Finally I found the reason. When you open a terminal from atom-terminal, you get these environment variables set:

```
ATOM_HOME=/home/user/.atom
GOOGLE_API_KEY=3h4kjhb4go9h4ntgwk
NODE_PATH=/usr/share/atom/resources/app.asar/exports
CHROME_DESKTOP=Atom.desktop
NODE_ENV=production
```

I don't know why this is done, but I understand that for a general use of a terminal at least `GOOGLE_API_KEY` ,`NODE_PATH` and `NODE_ENV` shouldn't be there. They can (and do) corrupt the terminal environment.

**Comment by tkw1536** [comment]
These come from the fact that atom sets them (some of them are needed for the apm modules I believe). 
When we fork to start a terminal process these are just inherited. We could propably unset them explicitly, but I'm not sure thats the right approach. 
Something similar came up in issue #13.

**Comment by rubencaro** [comment]
@tkw1536 Thanks! I got it working with (`/bin/terminator` is my weapon of choice):

```
    app: "/bin/bash"
    args: "-c 'unset NODE_ENV && unset NODE_PATH && /bin/terminator'"
```

**Comment by stevehanson** [comment]
@rubencaro Which file is that that you edited in your comment above?

**Comment by rubencaro** [comment]
@stevehanson none! That were just on the settings view inside atom.

**Comment by stevehanson** [comment]
@rubencaro thanks for the quick reply. I'm still not seeing those options. Are they in the global Atom settings, or the Terminal Status settings, or elsewhere? Thanks for the help :)

**Comment by rubencaro** [comment]
It's on atom-terminal own settings. `app` and `args` are the options.

**Comment by stevehanson** [comment]
OK. All I see is Window Height:

![image](https://cloud.githubusercontent.com/assets/1691324/9023236/c2f645de-3858-11e5-8b54-949fe1cda677.png)

I'm brand new to Atom. Probably need to just spend a bit more time in it before asking these newb questions.

**Comment by stevehanson** [comment]
ok, I just found where I can edit the raw `config.cson`.
