### ISSUE TITLE
Keybindings is not available on v0.8.0

### ISSUE THREAD

**Issue by axsann** [karan/atom-terminal#54]
I've used atom-terminal... but since I updated it to v0.8.0, Terminal does not open with ctrl-shift-t.
I considered conflicting keybindings, but setting->keybindings is not conflicting.
Please modify.
OS: OSX Yosemite
Atom-Version: 0.201.0

**Comment by axsann** [comment]
Solved!!
Modify package.json as follows. 

"activationCommands": {
    "atom-workspace": [
      "atom-terminal:open",
      "atom-terminal:open-project-root"
    ]
  },

"atom-terminal:open",   is added line.

**Comment by bobrocke** [comment]
That makes sense. And it works. But `open` and `open-project-root` open to the same place. :(

Do I have something else wrong somewhere?

**Comment by axsann** [comment]
In my case, it works with no problem in OSX.
I guess your project has no subdirectory, hasn't it?
Try in atom-terminal project. and select [atom-terminal.coffee] under [lib] directory.
And  pressed ctrl-shift-t opens [~/.atom/packages/atom-terminal/lib] (directory existing file)
alt-shift-t opens [~/.atom/packages/atom-terminal](project root).
How about?

**Comment by bobrocke** [comment]
For me, `alt-shift-t` opens my root directory, `~/`.

`ctrl-shift-t`does the same!

![atom-terminal - atom](https://cloud.githubusercontent.com/assets/2962426/7788054/fbf69988-01f8-11e5-8119-fc74b44e1a12.jpg)

**Comment by axsann** [comment]
I see I see! That issue is #52.
Open settings and uncheck <Surpress Directory Argument>.
That is real solution!!

**Comment by bobrocke** [comment]
Indeed, that fixes the `open-project-root` opening the wrong directory!

Fortunately, that's the main thing I need because `open` still does nothing.

**Comment by bobrocke** [comment]
Does anyone know what might be wrong with my configuration if `open-project-root` works, but `open` doesn't?

**Comment by axsann** [comment]
Thanks!
