### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [karan/atom-terminal#58]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.8.0`) of this package:

1. Requiring `$` from `atom` is no longer supported. If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead: `{$} = require 'atom-space-pen-views'` or `$ = require 'jquery'` Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies. Or add `"jquery": "^2"` to your package dependencies.
1. Requiring `$$` from `atom` is no longer supported. Please require `atom-space-pen-views` instead: `{$$} = require 'atom-space-pen-views'` Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
1. Requiring `View` from `atom` is no longer supported. Please require `atom-space-pen-views` instead: `{View} = require 'atom-space-pen-views'` Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
1. The context menu CSON format has changed. Please see https://atom.io/docs/api/latest/ContextMenuManager#context-menu-cson-format for more info.

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by tkw1536** [comment]
I can't see any $ , $$ or View in https://github.com/karan/atom-terminal/blob/master/lib/atom-terminal.coffee and that is the only code file we have. 

The context menu CSON format was updated with in the last pull request. 

Where are these errors / deprecations coming from?

**Comment by benogle** [comment]
It's coming from analytics. There may be some misattribution of package names going on. Sorry about this. Feel free to close.
