### ISSUE TITLE
Cannot support open Iterm2 on current file's directory 

### ISSUE THREAD

**Issue by adaiguoguo** [karan/atom-terminal#61]
Cannot support open Iterm2 on current file's directory .
My app setting is:
/Applications/iTerm.app

Would I put something in Args?

**Comment by aioue** [comment]
+1

It just opens my user  folder.

**Comment by Undistraction** [comment]
Same here. Just opens at my user directory.

**Comment by tkw1536** [comment]
@Undistraction AFAIK unsetting "supressDirectoryArgument" should fix it. In 0.8.1 (which is not published to [atom.io/packages](https://atom.io/packages) yet @karan) this should be disabled by default.

**Comment by entotsu** [comment]
@tkw1536 Thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
